### ISSUE TITLE
Formatierung der Beträge bei Coins mit geringem Wert

### ISSUE THREAD

**Issue by weyandch** [Fransenson/PyT_Notifier#1]
Folgende Nachricht eben bekommen:

`: BOUGHT: 
Coin: IOSTETH
Total amount: 1249.0
Date: 5.4.2018 - 18:3
Average Price: 7.222323458767015e-05
Current Price: 7.18e-05
`

Gerundete Werte wären ne feine Sache :)

**Comment by Fransenson** [comment]
Die Werte werden 1:1 aus der .json übernommen. 0,00007xxx wäre ja auch korrekt als Preis. Ich schau nochmal, dass ich da die richtigen Datentypen nutze.

**Comment by Fransenson** [comment]
Fixed with latest update
